### ISSUE TITLE
installation error using python 3.12

### ISSUE THREAD

**Issue by wolass** [ralphbean/bugwarrior#1050]
Installation of bugwarrior depends on readfp which is not available for pythin 3.12...

Therefore I am getting a following error:

```
AttributeError: 'BugwarriorConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

```

reference link: 
https://bugs.launchpad.net/lazr.restfulclient/+bug/2041407

Tested 2 installation options: source and apt package for ubuntu. 
Tested 2 versions of bugwarrior 1.7 and 1.8 

all giving the same error. 

What can be done here?

**Comment by ryneeverett** [comment]
A few options:

1. Use python<3.12.
2. Use a development version of bugwarrior from the last 6 months.
3. Patch bugwarrior-1.8. This shouldn't be very involved. See #1019.

**Comment by lelixn** [comment]
This is caused by Python 3.12 .

Temporary workaround:
• use Python 3.11 or below  
• or modify the source and replace `readfp()` → `read_file()`

Once this change is applied in the codebase, installation should work fine on 3.12.

**Comment by ryneeverett** [comment]
IMO the more reasonable solution now is to use bugwarrior-2.0.0 which supports python 3.12 and 3.13.
