### ISSUE TITLE
no Bugzilla get_history method

### ISSUE THREAD

**Issue by djmitche** [ralphbean/bugwarrior#668]
With Bugwarrior-1.7.0:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior/services/__init__.py", line 499, in _aggregate_issues
    for issue in service.issues():
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior/services/bz.py", line 295, in issues
    extra['assigned_on'] = self._get_assigned_date(issue)
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior/services/bz.py", line 306, in _get_assigned_date
    history = bug.get_history()['bugs'][0]['history']
  File "/usr/local/lib/python2.7/dist-packages/bugzilla/bug.py", line 115, in __getattr__
    raise AttributeError(msg)
AttributeError: Bug object has no attribute 'get_history'.
If 'get_history' is a bugzilla attribute, it may not have been cached when the bug was fetched. You may want to adjust your include_fields for getbug/query.
```

I'm using the latest python-bugzilla (2.2.0) which, indeed, does not have a `get_history` method.  It does, however, have `get_history_raw` which is described as an experimental feature.  It looks like this code was introduced in #648 /cc @mathiashls and @beav 

Is this a feature of an older or newer python-bugzilla?  Or is it an XMLRPC call that some bugzilla instances (such as Mozilla's in this case) don't support?

Noe that the patch [only seems to look at the last element in the bug history](https://github.com/ralphbean/bugwarrior/pull/405#discussion_r288301972), too.

**Comment by ralphbean** [comment]
I can duplicate the traceback locally.

**Comment by ralphbean** [comment]
I see Cole mention the rename here:  https://blog.wikichoon.com/2016/06/python-bugzilla-api-changes-in-git.html

**Comment by ssbarnea** [comment]
Maybe it would make sense to add an integration testing suite that talks with instances like https://bugzilla.redhat.com so we would findout when it breaks and fix it quickly.

**Comment by djmitche** [comment]
That's a little tricky since each bz instance has its own customizations -- it'd be very easy to add something that's specific to the redhat bz and not notice.

In this case, the incompatibility is with the python-bugzilla library.  Somehow a patch landed for bugwarrior that used an as-yet-unreleased version of python-bugzilla.  Catching *that* in the bugwarrior tests seems like a good improvement.

**Comment by Mossop** [comment]
Is it possible get a release out with this fix in it?

**Comment by pierreprinetti** [comment]
>Is it possible get a release out with this fix in it?

/bump

@ralphbean ? :pray:
