### PR TITLE
Fix python-bugzilla usage for setting assigned-on date.

### LINKED ISSUE #668: no Bugzilla get_history method
With Bugwarrior-1.7.0:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior/services/__init__.py", line 499, in _aggregate_issues
    for issue in service.issues():
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior/services/bz.py", line 295, in issues
    extra['assigned_on'] = self._get_assigned_date(issue)
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior/services/bz.py", line 306, in _get_assigned_date
    history = bug.get_history()['bugs'][0]['history']
  File "/usr/local/lib/python2.7/dist-packages/bugzilla/bug.py", line 115, in __getattr__
    raise AttributeError(msg)
AttributeError: Bug object has no attribute 'get_history'.
If 'get_history' is a bugzilla attribute, it may not have been cached when the bug was fetched. You may want to adjust your include_fields for getbug/query.
```

I'm using the latest python-bugzilla (2.2.0) which, indeed, does not have a `get_history` method.  It does, however, have `get_history_raw` which is described as an experimental feature.  It looks like this code was introduced in #648 /cc @mathiashls and @beav 

Is this a feature of an older or newer python-bugzilla?  Or is it an XMLRPC call that some bugzilla instances (such as Mozilla's in this case) don't support?

Noe that the patch [only seems to look at the last element in the bug history](https://github.com/ralphbean/bugwarrior/pull/405#discussion_r288301972), too.

### PR DESCRIPTION
**Pull request by ralphbean**
Fixes #668.

Cole renamed this in version 2.0.0.  That was quite a while ago, so let's just
push the minimum requirement up to that as a baseline and use the new method
name.

### CODE REVIEW

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
While this fixes the initial error, it still fail to do a pull on redhat.bugzilla.com:
```
ERROR:bugwarrior.services:Worker for [bz] failed: 'NoneType' object has no attribute 'timetuple'
Traceback (most recent call last):
File "/Users/ssbarnea/rdo/bugwarrior/bugwarrior/services/__init__.py", line 499, in _aggregate_issues
for issue in service.issues():
File "/Users/ssbarnea/rdo/bugwarrior/bugwarrior/services/bz.py", line 295, in issues
extra['assigned_on'] = self._get_assigned_date(issue)
File "/Users/ssbarnea/rdo/bugwarrior/bugwarrior/services/bz.py", line 316, in _get_assigned_date
assigned_date_datetime = datetime.datetime.fromtimestamp(time.mktime(assigned_date.timetuple()))
AttributeError: 'NoneType' object has no attribute 'timetuple'
```

**Comment by ralphbean** [comment]
Thanks @ssbarnea.  Fixing in a subsequent commit in a moment.
